{% set name = 'jupyter_highlight_selected_word' %}
{% set version = '0.0.11' %}
{% set sha256 = '3e0ae5f27f9f9e7b2de64b65ab5bc8d77481c4b95ee95b852adc48772932465d' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - jupyter_contrib_core >=0.3
    - notebook >=4.0

test:
  imports:
    - jupyter_highlight_selected_word

about:
  summary: |
    Jupyter notebook extension that enables highlighting of all instances of
    the currently-selected or cursor-adjecent word in either the current cell's
    editor, or in the whole notebook.
    Based on the  CodeMirror addon
    https://codemirror.net/demo/matchhighlighter.html
    extended to work across multiple editors.
  home: https://github.com/jcb91/jupyter_highlight_selected_word
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91
