appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: b/dzlYwNngleerHb4dxRdgbrBOdlufI92FgTwHzouWfS/Q2vN5IuTREW5YPYydMuYAewjUkd7gCb6u4fuDewrn9o0OmbEXXrfI24ZdyMbDsf4dcsRqbHCmgKq73uPuREy00b/jjCDam7CW+ZE8NZfRagYZM5JtwT/YUPBjUkgAJTGN43X06oPzCpGgBvlcPvfzG+/FIGwlUIp+qKr8p0hNVNRdctjRvEbpkPplXCMo/mb4W0QYeCTuCSMPfLR0z63UNETGkGFxHTZSLuEXNNkSLK99RJx6tq8fxxrEX2EFwzLIhOPWXO9EWUeDGzYpbVR3/tfOzQHW7YyLYOTd+xo3DNaE4Mpf7F8EplhjRPQwc/7HmlkaR6Pb8gR1otpjWY+jiHi4U8YLPnyukAENczrJipb9JqdH7beTb4ZmLZ8IGVahfsn1CYSTd8jegvpQkK3hJkMhQCmV0IwkoCGqi0H5sgjQ8vtOERAu6ydqdZVkjae0gwr4+EVSJ0r63X57qHIVNwZZUcxFsRurI68lg6us/pF4/5Wl6zasOyhL/kYnquz5NVHto+tET8kAcWsT/r/H8jQmFnS734f3hmljfd9kfZGH9cbLQ5e4Kmp90+TJgAajjgMM4EP4sOPLabskejakoTUsDv1/0ogbMhnabxrZKfPB6fjvS/yAKqwQY25+w=}
